name: Array.sortOn
author: gonchuki
category: Native
tags: [array, sort, keys, sortOn, actionscript, sorting]
docs: http://www.adobe.com/livedocs/flash/9.0/ActionScriptLangRefV3/Array.html#sortOn()
demo: http://www.jsfiddle.net/5e7yc/
current: 1.0